### ISSUE TITLE
No such method: removeOnGlobalLayoutListener

### ISSUE THREAD

**Issue by micku7zu** [micku7zu/Locate-driver#2]
java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeOnGlobalLayoutListener
    at com.micutu.locatedriver.Fragments.SettingsCardFragment$1.onGlobalLayout(SettingsCardFragment.java:47)
    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:566)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1720)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2632)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4517)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
    at dalvik.system.NativeStart.main(Native Method)

Replace removeOnGlobalLayoutListener with removeGlobalOnLayoutListener for older Android devices.

**Comment by micku7zu** [comment]
Fixed 90aabddcf6ce846cca99b7a87fe23d2e712e5e3c
