### ISSUE TITLE
java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.

### ISSUE THREAD

**Issue by micku7zu** [micku7zu/Locate-driver#4]
```
java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
    at android.os.Parcel.readException(Parcel.java:1620)
    at android.os.Parcel.readException(Parcel.java:1573)
    at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
    at com.google.android.gms.internal.zzpr$zza.zzb(Unknown Source)
    at com.google.android.gms.internal.zzqa.zzf(Unknown Source)
    at com.google.android.gms.internal.zzqa.zzd(Unknown Source)
    at com.google.android.gms.internal.zzqf.zzd(Unknown Source)
    at com.google.android.gms.internal.zzqd.zzd(Unknown Source)
    at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
    at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.startUpdating(LocationGooglePlayServicesProvider.java:136)
    at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnected(LocationGooglePlayServicesProvider.java:177)
    at com.google.android.gms.common.internal.zzl.zzo(Unknown Source)
    at com.google.android.gms.internal.zzqd.zzm(Unknown Source)
    at com.google.android.gms.internal.zzqb.zzapm(Unknown Source)
    at com.google.android.gms.internal.zzqb.onConnected(Unknown Source)
    at com.google.android.gms.internal.zzqf.onConnected(Unknown Source)
    at com.google.android.gms.internal.zzpu.onConnected(Unknown Source)
    at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
    at com.google.android.gms.common.internal.zzd$zzj.zzarz(Unknown Source)
    at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
    at com.google.android.gms.common.internal.zzd$zza.zzx(Unknown Source)
    at com.google.android.gms.common.internal.zzd$zze.zzasb(Unknown Source)
    at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by micku7zu** [comment]
Fixed 3b308020e5d6ba2ff3c050f7f17ea73f892b004f
