### ISSUE TITLE
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.HtcContactsProvider2 

### ISSUE THREAD

**Issue by micku7zu** [micku7zu/Locate-driver#5]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content: (has extras) }} to activity {com.micutu.locatedriver/com.micutu.locatedriver.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.HtcContactsProvider2 from ProcessRecord{333e1324 1533:com.micutu.locatedriver/u0a208} (pid=1533, uid=10208) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3881)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3931)
    at android.app.ActivityThread.access$1300(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:155)
    at android.app.ActivityThread.main(ActivityThread.java:5696)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.HtcContactsProvider2 from ProcessRecord{333e1324 1533:com.micutu.locatedriver/u0a208} (pid=1533, uid=10208) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
    at android.os.Parcel.readException(Parcel.java:1549)
    at android.os.Parcel.readException(Parcel.java:1502)
    at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3346)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:5020)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2566)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1463)
    at android.content.ContentResolver.query(ContentResolver.java:475)
    at android.content.ContentResolver.query(ContentResolver.java:435)
    at com.micutu.locatedriver.MainActivity.onActivityResult(MainActivity.java:197)
    at android.app.Activity.dispatchActivityResult(Activity.java:6160)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3877)
    ... 10 more
```

**Comment by micku7zu** [comment]
Fixed 3b308020e5d6ba2ff3c050f7f17ea73f892b004f
